import assert from "node:assert/strict";
import { parseGitHubIssueUrl, renderProofMarkdown, type ProofInput } from "../src/index.js";

const issue = parseGitHubIssueUrl("https://github.com/P-r-e-m-i-u-m/proof-bot/issues/1");

assert.equal(issue.owner, "P-r-e-m-i-u-m");
assert.equal(issue.repo, "proof-bot");
assert.equal(issue.number, 1);
assert.equal(issue.kind, "issue");

const input: ProofInput = {
  issue,
  title: "Proof of Work",
  summary: "Implemented the requested CLI behavior and verified it locally.",
  commits: ["abc1234 Add dry-run mode"],
  checks: ["npm test passed", "GitHub Actions passed"],
  files: ["src/cli.ts", "tests/smoke.test.ts"],
  links: ["https://github.com/P-r-e-m-i-u-m/proof-bot/actions"],
  risks: ["GitHub commenting requires GITHUB_TOKEN."],
  nextSteps: ["Add repository auto-discovery."],
  generatedAt: "2026-05-09T00:00:00.000Z"
};

const markdown = renderProofMarkdown(input, {
  title: "Add dry-run mode",
  state: "open",
  url: issue.url,
  labels: ["enhancement"]
});

assert.match(markdown, /Proof of Work: Add dry-run mode/);
assert.match(markdown, /npm test passed/);
assert.match(markdown, /src\/cli.ts/);
assert.match(markdown, /Generated by Proof Bot/);

console.log("Smoke tests passed.");
