import type { GitHubIssueSummary, ProofInput } from "./types.js";

const renderList = (items: string[], emptyText: string): string =>
  items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : `- ${emptyText}`;

export function renderProofMarkdown(input: ProofInput, issue?: GitHubIssueSummary): string {
  const title = input.title ?? "Proof of Work";
  const targetTitle = issue?.title ? `: ${issue.title}` : "";

  return `## ${title}${targetTitle}

${input.summary ?? "This comment records the evidence used to verify the work."}

| Field | Value |
| --- | --- |
| Target | [${input.issue.owner}/${input.issue.repo}#${input.issue.number}](${input.issue.url}) |
| Type | ${input.issue.kind} |
| State | ${issue?.state ?? "not fetched"} |
| Generated | ${input.generatedAt} |

### Implementation Evidence

${renderList(input.commits, "No commits were provided.")}

### Verification

${renderList(input.checks, "No verification checks were provided.")}

### Changed Files

${renderList(input.files, "No changed files were provided.")}

### Supporting Links

${renderList(input.links, "No supporting links were provided.")}

### Risks And Follow-Up

${renderList(input.risks, "No known risks were recorded.")}

### Next Steps

${renderList(input.nextSteps, "No next steps were recorded.")}

---

Generated by Proof Bot.`;
}
